#!/bin/bash

if [ "$#" -lt 3 ]
then
 echo "Usage $0 <subjid/list> <in_dir> <out_dir>"
 exit 0
fi

if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$1
fi 

for subj in $subjids
do 
 
subj_dir=$2/$subj
out_dir=$3/$subj

mkdir -p $out_dir

tck=$subj_dir/dwi/mrtrix3/tractography/SingleShell_CSDTracking/CSDProb_WholeBrainTracks_in_FODTemplateSpace.tck
vtk=$out_dir/wholebrain.vtk
bfloat=$out_dir/wholebrain.bfloat

runMatlabCmd convertTractsMRTrixToVTK "'$tck'" "$vtk"

runMatlabCmd convertTractsMRTrixToCamino "'$tck'" "$bfloat"

echo cp $tck $out_dir/wholebrain.tck
cp $tck $out_dir/wholebrain.tck

done #subj 
