#!/bin/bash

if [ "$#" -lt 1 ]
then
 echo "Usage $0 <subjid/list> <in_dir>"
 exit 0
fi

if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$1
fi

for subj in $subjids
do 

subj_dir=$2/$subj
dwi_dir=$subj_dir/dwi

# Variables
dwi=$dwi_dir/dwi.nii.gz
scheme=$dwi_dir/dwi.scheme
bfloat=$dwi_dir/dwi.bfloat
dti=$dwi_dir/dti.bdouble
bval=$dwi_dir/dwi.bval
bvec=$dwi_dir/dwi.bvec
mask=$dwi_dir/dwi_brainmask.nii.gz

# Generate schemefile
echo fsl2scheme -bvecfile $bvec -bvals $bval -zerobval 5 > $scheme
fsl2scheme -bvecfile $bvec -bvals $bval -zerobval 5 > $scheme 

# Convert image to bfloat
echo image2voxel -4dimage $dwi -outputfile $bfloat
image2voxel -4dimage $dwi -outputfile $bfloat

# Fit tensors
echo wdtfit $bfloat $scheme -bgmask $mask -outputfile $dti
wdtfit $bfloat $scheme -bgmask $mask -outputfile $dti

# Compute maps
for PROG in fa md; do
 cat $dti | ${PROG} | voxel2image -outputroot ${PROG} -header $dwi
done 

rm -f $bfloat $scheme $dti

done #subj 
